### ISSUE TITLE
TypeError when running the script

### ISSUE THREAD

**Issue by shanirub** [sibbl/sachsen-impfnotifier#5]
Hi there,

I've git cloned the repo and followed the instructions in README.md.

However, when i tried running the script from the command line:
`PASSWORD='somepasswd' USER_NAME='someusername' CENTERS='center1,center2,center3' node index.js`

I got this error message:
```
(node:390666) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at /home/srub/Dokumente/code/repos/code/sachsen-impfnotifier/index.js:5:39
    at Object.<anonymous> (/home/srub/Dokumente/code/repos/code/sachsen-impfnotifier/index.js:50:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:390666) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:390666) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Could you please help me? What am I doing wrong?

**Comment by sibbl** [comment]
@shanirub which command line are you using? It seems that the environment variables are not passed correctly and thus `process.env.CENTRES` is undefined when `split` is called on it in line 5 of `index.js`.

**Comment by shanirub** [comment]
ohmyzsh on fedora

**Comment by sibbl** [comment]
@shanirub took me a while, but it seems like a typo is the problem here :) `CENTRES` instead of `CENTERS` (first R, then E).

Let me know if this solves it.

**Comment by shanirub** [comment]
Yes! Works now.
Thanks!
